const express = require("express");
const router = express.Router();
const { register, login, getMe } = require("../controllers/authController");
const { registerValidation, loginValidation } = require("../validations/authValidation");
const { protect } = require("../middlewares/auth");
const { authLimiter } = require("../middlewares/rateLimiter");
router.post("/register",authLimiter,registerValidation, register);
router.post("/login", authLimiter,loginValidation, login);
router.get("/me", protect, getMe);
module.exports = router;